In [1]:
# import libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
dataset= pd.read_csv('loan_approval_dataset.csv')
dataset.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [3]:
dataset.shape

(4269, 13)

In [4]:
dataset.nunique()

loan_id                      4269
 no_of_dependents               6
 education                      2
 self_employed                  2
 income_annum                  98
 loan_amount                  378
 loan_term                     10
 cibil_score                  601
 residential_assets_value     278
 commercial_assets_value      188
 luxury_assets_value          379
 bank_asset_value             146
 loan_status                    2
dtype: int64

In [5]:
dataset[dataset.duplicated()]

Empty DataFrame
Columns: [loan_id,  no_of_dependents,  education,  self_employed,  income_annum,  loan_amount,  loan_term,  cibil_score,  residential_assets_value,  commercial_assets_value,  luxury_assets_value,  bank_asset_value,  loan_status]
Index: []

In [6]:
dataset.drop(columns = "loan_id",inplace=True)

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0    no_of_dependents          4269 non-null   int64
 1    education                 4269 non-null   object
 2    self_employed             4269 non-null   object
 3    income_annum              4269 non-null   int64
 4    loan_amount               4269 non-null   int64
 5    loan_term                 4269 non-null   int64
 6    cibil_score               4269 non-null   int64
 7    residential_assets_value  4269 non-null   int64
 8    commercial_assets_value   4269 non-null   int64
 9    luxury_assets_value       4269 non-null   int64
 10   bank_asset_value          4269 non-null   int64
 11   loan_status               4269 non-null   object
dtypes: int64(9), object(3)
memory usage: 400.3+ KB

In [8]:
dataset.columns = [c.strip() for c in dataset.columns] # Fix Column names

In [9]:
y = dataset['loan_status'].copy()

In [10]:
X = dataset.drop(columns = ["loan_status"])

In [11]:
X.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value'],
      dtype='object')

In [12]:
# Duplicates --> no duplicates
X[X.duplicated()]

Empty DataFrame
Columns: [no_of_dependents, education, self_employed, income_annum, loan_amount, loan_term, cibil_score, residential_assets_value, commercial_assets_value, luxury_assets_value, bank_asset_value]
Index: []

In [13]:
# Missing Value analysis
X.isna().sum()

no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
dtype: int64

In [14]:
X.nunique()

no_of_dependents              6
education                     2
self_employed                 2
income_annum                 98
loan_amount                 378
loan_term                    10
cibil_score                 601
residential_assets_value    278
commercial_assets_value     188
luxury_assets_value         379
bank_asset_value            146
dtype: int64

In [15]:
X.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000

In [16]:
X.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value'],
      dtype='object')

In [17]:
# preprocessing as per the domain knowledge
X['total_assets_value'] =  X['residential_assets_value'] + X['commercial_assets_value'] + X['luxury_assets_value'] + X['bank_asset_value']

# drop the Columns
X.drop(columns=['residential_assets_value','commercial_assets_value', 'luxury_assets_value','bank_asset_value' ],inplace=True)

In [18]:
X.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,total_assets_value
0,2,Graduate,No,9600000,29900000,12,778,50700000
1,0,Not Graduate,Yes,4100000,12200000,8,417,17000000
2,3,Graduate,No,9100000,29700000,20,506,57700000
3,3,Graduate,No,8200000,30700000,8,467,52700000
4,5,Not Graduate,Yes,9800000,24200000,20,382,55000000

In [19]:
X.education.unique()

array([' Graduate', ' Not Graduate'], dtype=object)

In [20]:
X.self_employed.unique()

array([' No', ' Yes'], dtype=object)

In [21]:
y.unique()

array([' Approved', ' Rejected'], dtype=object)

In [22]:
X['education'] = X['education'].str.strip()
X['self_employed'] = X['self_employed'].str.strip()
y = y.str.strip()

In [23]:
X.self_employed.unique()

array(['No', 'Yes'], dtype=object)

In [24]:
import pandas as pd
def separate_column_types(df):
    numerical_columns = []
    string_columns = []

    for col in df.columns:
        if df[col].dtype == "object":
            string_columns.append(col)
        else :
            numerical_columns.append(col)

    return numerical_columns, string_columns

num_cols, cat_cols = separate_column_types(X)

print("Numerical columns:", num_cols)
print("String columns:", cat_cols)

Numerical columns: ['no_of_dependents', 'income_annum', 'loan_amount', 'loan_term', 'cibil_score', 'total_assets_value']
String columns: ['education', 'self_employed']

In [25]:
# Transformation to Binary
def transform_categorical_to_binary(df, columns_to_transform):
  """
  Transforms specified categorical columns in a DataFrame to binary (0 and 1).

  Args:
    df: The DataFrame to modify.
    columns_to_transform: A dictionary where keys are column names and values are 
                          lists of the original categorical values to map to 1.

  Returns:
    The modified DataFrame with transformed columns.
  """

  for column_name, positive_values in columns_to_transform.items():
    df[column_name] = df[column_name].apply(lambda x: 1 if x in positive_values else 0)

  return df

columns_to_transform = {
  'education': ['Graduate'],
  'self_employed': ['Yes']
}

transformed_X = transform_categorical_to_binary(X, columns_to_transform)
transformed_X

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,total_assets_value
0,2,1,0,9600000,29900000,12,778,50700000
1,0,0,1,4100000,12200000,8,417,17000000
2,3,1,0,9100000,29700000,20,506,57700000
3,3,1,0,8200000,30700000,8,467,52700000
4,5,0,1,9800000,24200000,20,382,55000000
...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,7400000
4265,0,0,1,3300000,11300000,20,559,20000000
4266,2,0,0,6500000,23900000,18,457,39000000
4267,1,0,0,4100000,12800000,8,780,28800000
4268,1,1,0,9200000,29700000,10,607,77300000

In [26]:
num_cols

['no_of_dependents',
 'income_annum',
 'loan_amount',
 'loan_term',
 'cibil_score',
 'total_assets_value']

In [27]:
# log transformation
log_cols = ['income_annum','loan_amount','total_assets_value']
X[log_cols] = np.log(X[log_cols])

In [28]:
y = y.map({"Approved":1, "Rejected":0})

In [29]:
y

0       1
1       0
2       0
3       0
4       0
       ..
4264    0
4265    1
4266    0
4267    1
4268    1
Name: loan_status, Length: 4269, dtype: int64

In [30]:
# Split the dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3, random_state=0)

In [31]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(X_train,y_train)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [32]:
y_pred_test = log.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pred_test)
print(f"Accuracy is {acc}")

Accuracy is 0.9055425448868072

# Serialization and Deserialization

In [34]:
# serialization & deserialization
import joblib
joblib.dump(log,"my_trained_model_v1.pkl")

['my_trained_model_v1.pkl']

In [35]:
#deserialization
final_model = joblib.load("my_trained_model_v1.pkl")

In [36]:
final_model.intercept_, final_model.coef_

(array([-3.64586758]),
 array([[-0.02881411, -0.01387221,  0.04775529, -3.2164965 ,  2.30631769,
         -0.15443121,  0.02359636,  0.2563642 ]]))

In [37]:
log.intercept_, log.coef_

(array([-3.64586758]),
 array([[-0.02881411, -0.01387221,  0.04775529, -3.2164965 ,  2.30631769,
         -0.15443121,  0.02359636,  0.2563642 ]]))

## Package and Modules

In [62]:
import PackageA

In [63]:
from PackageA import f1

In [64]:
f1.print_something()

'output from f1'

In [65]:
from PackageA import f2

In [66]:
f2.print_something()

'output from f2'

In [67]:
from PackageA.f1 import print_something as f1p

In [68]:
f1p()

'output from f1'

In [69]:
from PackageA.SubPackageA import f3

In [70]:
f3.print_something()

'output from f3'

In [47]:
from PackageA.SubPackageB import f5
f5.print_something()

'output from f5'

# Adding the System Path

In [48]:
import sys

In [49]:
sys.path

['/opt/anaconda3/lib/python313.zip',
 '/opt/anaconda3/lib/python3.13',
 '/opt/anaconda3/lib/python3.13/lib-dynload',
 '',
 '/opt/anaconda3/lib/python3.13/site-packages',
 '/opt/anaconda3/lib/python3.13/site-packages/aeosa']

In [50]:
sys.path.append('/Users/akylbek/Desktop/') # mac or linux

In [51]:
#sys.path.append('C:\\path\\to\\dir') # windows

#  Getting the Parent Directory

In [52]:
import PackageA

In [53]:
PackageA.__file__

'/Users/akylbek/IdeaProjects/mlops/mlops/lecture5/packaging/Experiments/PackageA/__init__.py'

In [54]:
import pathlib
pathlib.Path(PackageA.__file__).resolve().parent

PosixPath('/Users/akylbek/IdeaProjects/mlops/mlops/lecture5/packaging/Experiments/PackageA')

# Create Custom Data Transformers

In [55]:
# Key thing --> Inherit - BaseEstimator, TransformerMixin
# implement fit and transform
# accept input with __init__ method

from sklearn.base import BaseEstimator,TransformerMixin

class DemoTransformer(BaseEstimator,TransformerMixin):
    def __init__(self):
        pass
    
    def fit(self,X,y=None):
        return self

    def transform(self,X):
        return X

In [56]:
from sklearn.base import BaseEstimator,TransformerMixin

class AddColumns(BaseEstimator,TransformerMixin):
    def __init__(self, columns_transform):
        self.columns_transform = columns_transform
        self.new_col = "new_column"
    
    def fit(self,X,y=None):
        return self

    def transform(self,X):
        X[self.new_col] = X[self.columns_transform].sum(axis=1)
        return X

In [57]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randint(0,100,(10,5)), columns=list("abcde"))
df

    a   b   c   d   e
0  19  46  19  78  75
1  22  23  18  84  46
2  79  54  38  58  13
3  84  96  57  54  73
4  31  97  47  58  31
5   6  29  65   0  41
6   6  24  51   1  71
7  44  13   1  86  41
8  88  17  28   6  96
9  56   1  53  36  25

In [58]:
column_add = AddColumns(["a","b","c","d"])
column_add.fit(df)

AddColumns(columns_transform=['a', 'b', 'c', 'd'])

In [59]:
column_add.transform(df)

    a   b   c   d   e  new_column
0  19  46  19  78  75         162
1  22  23  18  84  46         147
2  79  54  38  58  13         229
3  84  96  57  54  73         291
4  31  97  47  58  31         233
5   6  29  65   0  41         100
6   6  24  51   1  71          82
7  44  13   1  86  41         144
8  88  17  28   6  96         139
9  56   1  53  36  25         146

In [60]:
np.random.seed(0)
df = pd.DataFrame(np.random.randint(0,100,(10,2)),columns=["A",'B'])
df.iloc[1,0] = np.nan
df.iloc[2,1] = np.nan
df.iloc[3,1] = np.nan
df.iloc[4,0] = np.nan
df

      A     B
0  44.0  47.0
1   NaN  67.0
2  67.0   NaN
3  83.0   NaN
4   NaN  87.0
5  70.0  88.0
6  88.0  12.0
7  58.0  65.0
8  39.0  87.0
9  46.0  88.0

In [61]:
mean_imputer = MeanImputer(variables=["A",'B'])

NameError: name 'MeanImputer' is not defined

In [ ]:
mean_imputer.fit(df)

In [ ]:
mean_imputer.mean_dict

In [ ]:
df.mean()

In [ ]:
mean_imputer.transform(df)

In [ ]:
import numpy
numpy.__version__

In [ ]:
import pandas as pd
pd.__version__

In [ ]:
import joblib
joblib.__version__

In [ ]:
import sklearn
sklearn.__version__

In [ ]:
import scipy
scipy.__version__

In [ ]:
import setuptools
setuptools.__version__

In [ ]:
import wheel
wheel.__version__

In [ ]:
import pytest
from prediction_model.config import config
from prediction_model.processing.data_handling import load_dataset
from prediction_model.predict import generate_predictions

In [ ]:
def single_prediction():
    test_dataset = load_dataset(config.TEST_FILE)
    single_row = test_dataset[config.FEATURES][:1]
    result = generate_predictions(single_row)
    return result

In [ ]:
single_prediction()